import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const Header = ({ user, onLogout, onProfileClick, onViewChange, currentView, }) => {
    const navItems = [
        { id: 'list', label: 'Canchas', icon: '🎾' },
        { id: 'clubs', label: 'Clubs', icon: '🛡️' },
        { id: 'tournaments', label: 'Torneos', icon: '🏆' },
        { id: 'leaderboard', label: 'Ranking', icon: '📊' },
    ];
    return (_jsx("header", { className: "bg-white/80 backdrop-blur-sm sticky top-0 z-20 border-b border-slate-200", children: _jsxs("div", { className: "container mx-auto px-4 py-3 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-6", children: [_jsxs("button", { onClick: () => onViewChange('venues'), className: "flex items-center gap-2 group", children: [_jsxs("svg", { xmlns: "http://www.w3.org/2000/svg", className: "h-7 w-7 text-indigo-600", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", children: [_jsx("circle", { cx: "12", cy: "12", r: "10" }), _jsx("path", { d: "M12 8v4l3 3" })] }), _jsxs("span", { className: "text-xl font-extrabold tracking-tighter text-slate-900 hidden sm:block group-hover:text-indigo-600 transition-colors", children: ["Reserva", _jsx("span", { className: "text-indigo-600", children: "TuCancha" })] })] }), _jsx("nav", { className: "hidden lg:flex items-center gap-1", children: navItems.map((item) => (_jsxs("button", { onClick: () => onViewChange(item.id), className: `px-4 py-2 rounded-xl text-sm font-bold transition-all ${currentView === item.id
                                    ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-100'
                                    : 'text-slate-600 hover:bg-slate-100'}`, children: [_jsx("span", { className: "mr-1.5", children: item.icon }), item.label] }, item.id))) })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "hidden sm:flex items-center bg-indigo-50 px-3 py-1.5 rounded-xl border border-indigo-100", children: _jsxs("span", { className: "text-indigo-600 font-black text-sm", children: [user.points, " pts"] }) }), _jsxs("button", { onClick: onProfileClick, className: "flex items-center gap-2 p-1 rounded-full hover:bg-slate-100 transition-colors", children: [_jsx("span", { className: "text-sm font-semibold text-slate-700 hidden sm:block", children: user.name }), user.avatar ? (_jsx("img", { src: user.avatar, alt: user.name, className: "w-9 h-9 rounded-full object-cover border-2 border-white shadow-sm" })) : (_jsx("div", { className: "w-9 h-9 rounded-full bg-slate-200 flex items-center justify-center font-bold text-indigo-600", children: user.name.charAt(0) }))] }), _jsx("button", { onClick: onLogout, title: "Cerrar sesi\u00F3n", className: "p-2 rounded-full hover:bg-slate-100 transition-colors text-slate-500 hover:text-slate-800", children: _jsx("svg", { xmlns: "http://www.w3.org/2000/svg", className: "h-5 w-5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: "2", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" }) }) })] })] }) }));
};
