import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { VENUES } from '../constants';
export const TournamentSection = ({ tournaments, currentUserId, onJoinTournament, }) => {
    return (_jsxs("div", { className: "py-8 animate-fade-in space-y-8", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-3xl font-extrabold text-slate-900 tracking-tight", children: "Torneos & Competiciones" }), _jsx("p", { className: "text-slate-500 mt-1", children: "Particip\u00E1 en los eventos m\u00E1s importantes de tu zona y gan\u00E1 premios incre\u00EDbles." })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-8", children: tournaments.map((tournament) => {
                    const venue = VENUES.find((v) => v.id === tournament.venueId);
                    const isJoined = tournament.participants.includes(currentUserId);
                    return (_jsxs("div", { className: "bg-white rounded-3xl shadow-sm border border-slate-100 overflow-hidden hover:shadow-xl transition-all duration-300 flex flex-col md:flex-row", children: [_jsxs("div", { className: "md:w-1/3 relative min-h-[140px]", children: [_jsx("img", { src: venue?.image ||
                                            'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?q=80&w=800&auto=format&fit=crop', alt: tournament.name, className: "absolute h-full w-full object-cover" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-black/40 to-transparent" }), _jsx("div", { className: "absolute top-4 left-4 bg-amber-500 text-white px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest shadow-lg", children: tournament.status === 'upcoming'
                                            ? 'Próximamente'
                                            : tournament.status === 'ongoing'
                                                ? 'En Curso'
                                                : 'Finalizado' })] }), _jsxs("div", { className: "p-6 md:w-2/3 flex flex-col justify-between", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsx("span", { className: "text-indigo-600 text-xs font-black uppercase tracking-widest", children: tournament.level }), _jsx("span", { className: "text-slate-400 text-xs", children: tournament.date })] }), _jsx("h3", { className: "text-xl font-black text-slate-900 mb-1 leading-tight", children: tournament.name }), venue && (_jsxs("p", { className: "text-slate-500 text-sm mb-4 flex items-center gap-1", children: [_jsxs("svg", { xmlns: "http://www.w3.org/2000/svg", className: "h-4 w-4 text-slate-400", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: [_jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" }), _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M15 11a3 3 0 11-6 0 3 3 0 016 0z" })] }), venue.name] })), _jsxs("div", { className: "flex gap-4 mb-6", children: [_jsxs("div", { className: "bg-slate-50 px-4 py-2 rounded-2xl border border-slate-100", children: [_jsx("p", { className: "text-[10px] uppercase font-bold text-slate-400 tracking-widest", children: "Premio" }), _jsx("p", { className: "text-sm font-black text-slate-800", children: tournament.prize })] }), _jsxs("div", { className: "bg-slate-50 px-4 py-2 rounded-2xl border border-slate-100", children: [_jsx("p", { className: "text-[10px] uppercase font-bold text-slate-400 tracking-widest", children: "Inscritos" }), _jsxs("p", { className: "text-sm font-black text-slate-800", children: [tournament.participants.length, " / 16"] })] })] })] }), _jsx("button", { onClick: () => !isJoined && onJoinTournament(tournament.id), disabled: tournament.status !== 'upcoming' || isJoined, className: `w-full py-3 rounded-2xl font-black text-sm transition-all ${isJoined
                                            ? 'bg-green-100 text-green-700 cursor-default'
                                            : tournament.status === 'upcoming'
                                                ? 'bg-indigo-600 text-white shadow-indigo-200 shadow-lg hover:bg-indigo-700 hover:-translate-y-0.5'
                                                : 'bg-slate-100 text-slate-400 cursor-not-allowed'}`, children: isJoined
                                            ? '✓ Inscripto'
                                            : tournament.status === 'upcoming'
                                                ? 'Inscribirse Ahora'
                                                : 'Inscripciones Cerradas' })] })] }, tournament.id));
                }) })] }));
};
